# Generated by Django 4.2.4 on 2023-08-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(max_length=20, verbose_name='Seccion del artículo'),
        ),
    ]
